### ISSUE TITLE
В смысле я только зарегистрировался, а у меня кредит на 70к

### ISSUE THREAD

**Issue by MeidKoi** [periankl/BankPrikoloff#10]
![image](https://github.com/user-attachments/assets/49d6af64-8c4a-4f44-b69a-4ce583b311a7)

**Comment by periankl** [comment]
Здравствуйте! Простите за долгий ответ. 
Нам жаль, что вы столкнулись с трудностями при использовании нашего сервиса. При создании аккаунта, согласно нашей оферте вам выдается бонусный кредит на 70 000₽. Отказаться от него нельзя

**Comment by periankl** [comment]
Пожалуйста, подскажите, мы можем вам еще чем-то помочь?
