### ISSUE TITLE
нЕ мОгУ зАрЕгИсТрИрОвАтЬсЯ!!!

### ISSUE THREAD

**Issue by MeidKoi** [periankl/BankPrikoloff#6]
![w-arknights-arknights](https://github.com/user-attachments/assets/ccc76bb0-74fd-485a-8074-9f6fe0d649df)

**Comment by periankl** [comment]
Здравствуйте! Нам жаль, что вы столкнулись со сложностями при использовании нашего сайта. Сервис находится на стадии активной разработки. Следите за обновлениями!
